package:
  format-version: "1.0.0"
  name: "core_apps_sam_9x7"
  version: "v3.2.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.19.5"
    - name: "core"
      type: "package"
      version: "v3.13.5"