format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_9X75_Evaluation_Board, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '0', y: '201', id: BSP_SAM_9X75_Evaluation_Board}
