format_version: v1.0
type: UniqueComponent
attributes: {id: dbgu}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: '144'}
  - type: Integer
    attributes: {id: DBGU_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: '266666666'}
  - type: Boolean
    attributes: {id: DBGU_INTERRUPT_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: 'true'}
  - type: KeyValueSet
    attributes: {id: DBGU_OPERATING_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: '1'}
  - type: Boolean
    attributes: {id: DBGU_RING_BUFFER_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: 'false'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: DBGU_UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_usart_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_usart_UART_dependency}
- type: ElementPosition
  attributes: {x: '248', y: '204', id: dbgu}
