configName: sam_9x75_curiosity_freertos
folderName: sam_9x75_curiosity_freertos
format_version: v1.0
frameworkPath: C:\microchip\harmony\h3
processor: SAM9X75
projectName: sam_9x75_curiosity_freertos
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAM9X7_DFP\1.1.120
